name: 'Publish Chrome extension to Chrome Web Store'
author: 'Mobile First LLC'
description: 'Upload and publish Chrome extensions to Chrome Web Store'
branding:
  icon: 'arrow-right'
  color: 'green'
inputs:
  action:
    description: 'Desired action, one of: upload, publish, testers'
    required: true
    default: 'upload'
  client_id:
    description: 'Webstore API client id parameter'
    required: true
  client_secret:
    description: 'Webstore API client secret parameter'
    required: true
  refresh_token:
    description: 'Webstore API refresh token'
    required: true
  zip_file:
    description: 'Path to extension .zip file'
    required: true
  extension_id:
    description: 'Unique identifier of the Chrome extension'
    required: true

outputs:
  result:
    description: 'Outcome of the requested upload action'

runs:
  using: 'node20'
  main: 'action/index.js'
