image: node:latest

stages:
  - install
  - deploy

install_dependencies:
  stage: install
  script: npm install
  artifacts:
    paths:
      - node_modules/

deploy:
  stage: deploy
  script:
    # run build steps
    - npm run build
    # upload to chrome web store
    - npx cws-upload $client_id $secret $token $zip_path $extension_id;
  artifacts:
    paths:
      - public/
  only:
    - tags
