language: node_js
node_js:
  - "latest"

script:
  - npm install

before_deploy:
  - npm run build

deploy:
  # on tagged commit upload .zip to chrome web store
  - if [ ! -z  "$TRAVIS_TAG" ]; then
      npx cws-upload $client_id $secret $token $zip $extension_id;
    fi
