language: node_js
node_js:
  - "latest"

script:
  - npm install
  - npm run build
  # require tagged commit
  # omit this condition to always upload
  - if [ ! -z  "$TRAVIS_TAG" ]; then
      npx cws-upload $client_id $secret $token $zip $extension_id;
    fi
