language: node_js
node_js:
  - "latest"

script:
  - npm install

before_deploy:
  - npm run build

deploy:
  # on tagged commit, upload release .zip
  # to Github release with matching tag
  - provider: releases
    skip_cleanup: true
    api_key: $github_token
    file: $zip
    on:
      tags: true

after_deploy:
  # on tagged commit,
  # upload release .zip to chrome web store
  - if [ ! -z  "$TRAVIS_TAG" ]; then
    npx cws-upload $cid $sec $tkn $zip $eid;
    fi
